export const FETCHING_IN_PROGRESS = 'FETCHING_IN_PROGRESS';
export const FETCHED_STATISTICS = 'FETCHED_STATISTICS';
export const FETCHING_CONNECTION_ERROR = 'FETCHING_CONNECTION_ERROR';
export const CHANGE_VIEW = 'CHANGE_VIEW';
